<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\settings\models\base;

use Yii;

/**
 * This is the base-model class for table "message".
 *
 * @property integer $id
 * @property string $language
 * @property string $translation
 *
 * @property \backend\modules\settings\models\SourceMessage $id0
 * @property string $aliasModel
 */
abstract class Message extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'language'], 'required'],
            [['id'], 'integer'],
            [['translation'], 'string'],
            [['language'], 'string', 'max' => 16],
            [['id', 'language'], 'unique', 'targetAttribute' => ['id', 'language']],
            [['id'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\modules\settings\models\SourceMessage::className(), 'targetAttribute' => ['id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'language' => 'Language',
            'translation' => 'Translation',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(\backend\modules\settings\models\SourceMessage::className(), ['id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\settings\models\query\MessageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\settings\models\query\MessageQuery(get_called_class());
    }


}
