<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\settings\models\base;

use Yii;

/**
 * This is the base-model class for table "source_message".
 *
 * @property integer $id
 * @property string $category
 * @property string $message
 *
 * @property \backend\modules\settings\models\Message[] $messages
 * @property string $aliasModel
 */
abstract class SourceMessage extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'source_message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message'], 'string'],
            [['category'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Category',
            'message' => 'Message',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(\backend\modules\settings\models\Message::className(), ['id' => 'id']);
    }


    /**
     * @inheritdoc
     * @return \backend\modules\settings\models\query\SourceMessageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\settings\models\query\SourceMessageQuery(get_called_class());
    }


}
