<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property string $user_email
 * @property string $name
 * @property string $description
 * @property string $ikey
 * @property string $amount
 * @property integer $quantity
 * @property string $availability
 * @property string $prod_condition
 * @property string $brand
 * @property integer $stock
 * @property string $image
 * @property integer $status
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Products extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['quantity', 'stock', 'status'], 'integer'],
            [['user_email', 'availability', 'prod_condition', 'brand', 'image'], 'string', 'max' => 100],
            [['name'], 'string', 'max' => 255],
            [['ikey', 'amount'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'user_email' => Yii::t('models', 'User Email'),
            'name' => Yii::t('models', 'Name'),
            'description' => Yii::t('models', 'Description'),
            'ikey' => Yii::t('models', 'Ikey'),
            'amount' => Yii::t('models', 'Amount'),
            'quantity' => Yii::t('models', 'Quantity'),
            'availability' => Yii::t('models', 'Availability'),
            'prod_condition' => Yii::t('models', 'Prod Condition'),
            'brand' => Yii::t('models', 'Brand'),
            'stock' => Yii::t('models', 'Stock'),
            'image' => Yii::t('models', 'Image'),
            'status' => Yii::t('models', 'Status'),
            'created_at' => Yii::t('models', 'Created At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ProductsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ProductsQuery(get_called_class());
    }


}
